"""Generate ``deploy/runpod/profiles.json`` (deploy.py reads JSON: it may only use Python + requests).

Contains, per profile: RunPod GPU type ids, minimum system RAM and the network-volume model budget
(sum of registry ``disk_gb`` for every model the profile references plus their fallback chains,
implemented or not, so the volume is sized for the finished system). CI checks the committed file is up to date.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from archrender.core.config import REPO_ROOT
from archrender.models.profiles import HardwareProfile
from archrender.models.registry import Registry

ASSETS_GB = 25.0
CACHES_GB = 15.0
DB_GB = 2.0
HEADROOM = 1.3
OUT = REPO_ROOT / "deploy" / "runpod" / "profiles.json"


def build() -> dict[str, object]:
    cfg = REPO_ROOT / "configs"
    reg = Registry.load(cfg)
    out: dict[str, object] = {
        "_comment": "generated by python -m archrender.ops.deploy_manifest; do not edit"
    }
    for name in ("gpu48", "gpu80", "gpu96plus"):
        prof = HardwareProfile.load(cfg, name)
        names: set[str] = set()
        for m in prof.roles.values():
            cur: str | None = m
            while cur is not None and cur not in names:  # role model + its fallback chain
                names.add(cur)
                cur = reg.get(cur).fallback
        models_gb = sum(reg.get(m).disk_gb for m in names)
        out[name] = {
            "gpu_types": prof.runpod_gpu_types,
            "min_system_ram_gb": prof.min_system_ram_gb,
            "vram_budget_gb": prof.vram_budget_gb,
            "models_gb": round(models_gb, 1),
            "assets_gb": ASSETS_GB,
            "caches_gb": CACHES_GB + DB_GB,
            "headroom": HEADROOM,
        }
    return out


def main(argv: list[str] | None = None) -> int:
    data = json.dumps(build(), indent=1, sort_keys=True) + "\n"
    if argv and argv[0] == "--check":
        if not OUT.exists() or OUT.read_text() != data:
            print(
                "deploy/runpod/profiles.json is stale: run python -m archrender.ops.deploy_manifest",
                file=sys.stderr,
            )
            return 1
        return 0
    Path(OUT).write_text(data)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
